// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiXKigx5S6JFbBTs-5okV6xqqiQfEIdzA',
    appId: '1:358321390599:web:3518a5c2f3f2d1737fd6a2',
    messagingSenderId: '358321390599',
    projectId: 'detail-keeping-app',
    authDomain: 'detail-keeping-app.firebaseapp.com',
    storageBucket: 'detail-keeping-app.appspot.com',
    measurementId: 'G-9GS8LETMWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWFDkhTDp3MgmFv-ZswjgPdMIy0JSW6AM',
    appId: '1:358321390599:android:5e0c6af2cb3e75597fd6a2',
    messagingSenderId: '358321390599',
    projectId: 'detail-keeping-app',
    storageBucket: 'detail-keeping-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_aBlL5OOXWwZ8rvJxI2MVaDOEHSM70Gk',
    appId: '1:358321390599:ios:0a10dba74b4729ae7fd6a2',
    messagingSenderId: '358321390599',
    projectId: 'detail-keeping-app',
    storageBucket: 'detail-keeping-app.appspot.com',
    iosClientId: '358321390599-1etf1jkep1tec0ea9hvit1l6755t8u4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_aBlL5OOXWwZ8rvJxI2MVaDOEHSM70Gk',
    appId: '1:358321390599:ios:0a10dba74b4729ae7fd6a2',
    messagingSenderId: '358321390599',
    projectId: 'detail-keeping-app',
    storageBucket: 'detail-keeping-app.appspot.com',
    iosClientId: '358321390599-1etf1jkep1tec0ea9hvit1l6755t8u4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
